### ISSUE TITLE
Can't get the volume up to 20% when using the skill. 

### ISSUE THREAD

**Issue by thewh1teagle** [hexeratops/mycroft-youtube-skill#2]
When i using this skill on my raspberry pi 4 with jack cable connected to speaker, 
everything works great but when i use this skill the maximum possible volume is 20%, i can change it manually in alsamixer to more than 20% but with voice control i can't.

**Comment by hexeratops** [comment]
Gotcha! I should be able to get this working pretty quickly :)

**Comment by hexeratops** [comment]
I think it should work now. Just call out "Change youtube volume to _____ percent" and Mycroft should read back what you said and play videos at your requested volume.

You should be able to change the default on [home.mycroft.ai](https://home.mycroft.ai/dashboard) as well. Please let me know if it works for you. (If it collides with another skill, try "increase/decrease youtube volume to 20")

**Comment by hexeratops** [comment]
(I'll leave this open until Friday, then close it unless I hear back.)
